# tags-dir: ~/.etags
# temp-dir: ~/.etags/temp
# etags-command: etags
skip-dirs:
  - ".*"
  - "__pycache__"
  - "*.egg-info"
projects:
  - name: update-etags
    path: /home/simon/workspace/update-etags
    file-types:
      - "*.py"
  - name: foo
    path: /home/simon/bar
    file-types:
      - "*.c"
      - "*.py"
